### ISSUE TITLE
Change postgres init from password to trust?

### ISSUE THREAD

**Issue by rsyring** [level12/keg-app-cookiecutter#100]
change in docker-compose.yaml:

```yaml
      environment:
        # Ok for local dev, potentially UNSAFE in other applications.  Don't blindly copy & paste
        # without considering implications.
        POSTGRES_HOST_AUTH_METHOD: trust
        # Could use this instead with a strong password if working outside a dev env
        # POSTGRES_PASSWORD: password
```

We just use a weak password anyway, so saves us a step from having to have the passwords in-sync.
