### ISSUE TITLE
Add mailhog to docker compose?

### ISSUE THREAD

**Issue by rsyring** [level12/keg-app-cookiecutter#185]
```yaml
version: '3.7'
services:
    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        logging:
            driver: 'none'  # disable saving logs
        ports:
            - '127.0.0.1:8025:8025'
            - '127.0.0.1:1025:1025'
 ```

/cc https://github.com/level12/marpps/issues/19
